"use client";
import { useRef, useState } from 'react';
import { statistics } from '../lib/analysis.mjs';
type Evidence={event_id:string;event_code:string;timestamp:string;goldstein_scale:number;avg_tone:number;actor1:{code:string;name:string}|null;actor2:{code:string;name:string}|null};
type Message={role:'user'|'assistant';content:string;stats?:ReturnType<typeof statistics>;mode?:string;eventIds?:string[]};
export default function AnalysisChat({events,mode,focus,onEvent,apiKey,onApiKeyChange}:{events:Evidence[];mode:'demo'|'live';focus:string;onEvent:(id:string)=>void;apiKey:string;onApiKeyChange:(key:string)=>void}){
 const key=apiKey,setKey=onApiKeyChange;
 const [question,setQuestion]=useState(''),[messages,setMessages]=useState<Message[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[settings,setSettings]=useState(false);
 const controller=useRef<AbortController|null>(null);
 const stats=statistics(events);
 async function send(e:React.FormEvent){e.preventDefault();if(!question.trim()||busy)return;if(!key.trim()){setSettings(true);setError('Add your own Anthropic key to ask a question.');return}const prompt=question.trim();const next:Message[]=[...messages,{role:'user',content:prompt}];setMessages(next);setQuestion('');setBusy(true);setError('');const abort=new AbortController();controller.current=abort;
 try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json','X-Anthropic-Api-Key':key},body:JSON.stringify({messages:next.slice(-11).map(({role,content})=>({role,content})),events,mode,focus}),signal:abort.signal});const result=await r.json();if(!r.ok)throw Error(result.error);setMessages(m=>[...m,{role:'assistant',content:result.text+(result.truncated?'\n\nResponse reached the length limit. Ask a follow-up to continue.':''),stats:result.statistics,mode,eventIds:events.map(e=>e.event_id)}]);}catch(e){if(!abort.signal.aborted){setError(e instanceof Error?e.message:'Unable to answer.');setQuestion(prompt);setMessages(m=>m.slice(0,-1));}}finally{setBusy(false);controller.current=null}}
 function clear(){controller.current?.abort();setMessages([]);setError('')}
 return <section className="analysis-chat" aria-label="World events conversation"><div className="chat-header"><div><div className="section-label">04 / ASK THE OBSERVATORY</div><h2>What might happen <em>next?</em></h2></div><div><button className="text-link" onClick={()=>setSettings(!settings)}>{key?'Key connected':'Bring your own key'} ↗</button><button className="text-link clear-chat" onClick={clear}>Clear chat</button></div></div><p className="chat-context">{mode==='demo'?'Synthetic scenario':'Loaded event sample'} · {events.length} records · {focus}. Can search the live web for current developments, cited by URL. Scenario reasoning, not a calibrated forecast.</p>
 <div className="stat-strip"><span><strong>{stats.events}</strong> observations</span><span><strong>{stats.conflictual}</strong> conflictual-coded</span><span><strong>{stats.cooperative}</strong> cooperative-coded</span><span><strong>{stats.averageGoldstein??'—'}</strong> mean Goldstein</span></div>
 {settings&&<div className="key-panel"><label>Anthropic API key<input type="password" autoComplete="off" spellCheck={false} value={key} onChange={e=>setKey(e.target.value)} placeholder="sk-ant-…"/></label><p>Kept only in this page’s memory. Sent through this server to Anthropic with your question and event sample. Your account pays for responses.</p><button className="text-link" onClick={()=>{setKey('');setSettings(false)}}>Forget key</button></div>}
 <div className="conversation" role="log" aria-live="polite" aria-label="Conversation">{messages.map((m,i)=><article className={'message '+m.role} key={i}><span className="section-label">{m.role==='user'?'YOU':`ASSISTANT / ${m.mode==='demo'?'SYNTHETIC SCENARIO':'SAMPLE ANALYSIS'}`}</span><div className="message-text">{m.content.split(/(\[[^\]\n]+\]|https?:\/\/[^\s)]+)/g).map((part,j)=>{if(part.startsWith('[')){const id=part.slice(1,-1);return m.eventIds?.includes(id)?<button key={j} className="citation" onClick={()=>onEvent(id)}>{part}</button>:part}return/^https?:\/\//.test(part)?<a key={j} className="citation" href={part} target="_blank" rel="noreferrer">{part}</a>:part})}</div>{m.stats&&<div className="answer-provenance">Snapshot: {m.stats.events} records · {m.stats.start?.slice(0,10)||'no dates'} · descriptive counts, not forecast probabilities</div>}</article>)}{busy&&<p className="thinking">Examining the evidence and strategic assumptions…</p>}</div>
 {!messages.length&&<div className="suggested-prompts">{['What does this sample actually tell us?','Compare incentives for cooperation and escalation.','Outline three scenarios and signals to watch.'].map(q=><button key={q} onClick={()=>setQuestion(q)}>{q} ↗</button>)}</div>}
 <form onSubmit={send}><label className="sr-only" htmlFor="world-question">Question about world events</label><textarea id="world-question" value={question} onChange={e=>setQuestion(e.target.value)} maxLength={4000} placeholder="Ask about an event, strategic incentives, or a possible outcome…" rows={3}/><div className="composer-bottom"><span>Evidence · Statistics · Strategic incentives · Scenarios</span><button type="submit" disabled={busy||!question.trim()}>{busy?'Thinking…':'Ask assistant'} ↑</button></div></form>{error&&<p role="alert" className="error">{error}</p>}</section>
}
