"use client";
import { useEffect, useMemo, useRef, useState } from 'react';
import type {WorldEvent,Actor} from '../lib/world';
type Node={id:string;x:number;y:number;label:string;actor?:Actor;event?:WorldEvent};
const hash=(s:string)=>Array.from(s).reduce((v,c)=>(v*31+c.charCodeAt(0))>>>0,7);
export default function KnowledgeGraph({events,visible,selected,actor,onActor,onEvent,labels=true}:{events:WorldEvent[];visible:WorldEvent[];selected:string|undefined;actor:string;onActor:(code:string)=>void;onEvent:(id:string)=>void;labels?:boolean}){
 const svg=useRef<SVGSVGElement>(null),stored=useRef(new Map<string,{x:number;y:number}>());
 const [camera,setCamera]=useState({x:0,y:0,scale:1}),[moved,setMoved]=useState<Record<string,{x:number;y:number}>>({});
 const drag=useRef<{id?:string;x:number;y:number;ox:number;oy:number;distance:number}|null>(null);
 const nodes=useMemo(()=>{
 const actors=Array.from(new Map(events.flatMap(e=>[e.actor1,e.actor2].filter((a):a is Actor=>!!a).map(a=>[a.code,a] as const))).values());
 const list:Node[]=actors.map((a,i)=>{const angle=i*2.399963;const r=100+Math.sqrt(i/Math.max(1,actors.length))*210;return{id:'a:'+a.code,label:a.name,actor:a,x:500+Math.cos(angle)*r,y:320+Math.sin(angle)*r*.78}});
 const map=new Map(list.map(n=>[n.id,n]));
 events.forEach(e=>{const a=e.actor1&&map.get('a:'+e.actor1.code),b=e.actor2&&map.get('a:'+e.actor2.code);const angle=hash(e.event_id)%628/100,r=30+hash(e.event_id)%75;list.push({id:'e:'+e.event_id,label:e.title||`Event ${e.event_code}`,event:e,x:(a&&b?(a.x+b.x)/2:a?a.x:b?b.x:500)+Math.cos(angle)*r,y:(a&&b?(a.y+b.y)/2:a?a.y:b?b.y:320)+Math.sin(angle)*r})});
 const old=stored.current;list.forEach(n=>{const p=old.get(n.id);if(p){n.x=p.x;n.y=p.y}});
 for(let k=0;k<60;k++)for(let i=0;i<list.length;i++)for(let j=i+1;j<list.length;j++){const a=list[i],b=list[j],dx=a.x-b.x||.01,dy=a.y-b.y||.01,d=Math.hypot(dx,dy),target=a.actor||b.actor?45:24;if(d<target){const f=(target-d)*.2/d;if(!old.has(a.id)){a.x+=dx*f;a.y+=dy*f}if(!old.has(b.id)){b.x-=dx*f;b.y-=dy*f}}}
 list.forEach(n=>{n.x=Math.max(55,Math.min(940,n.x));n.y=Math.max(55,Math.min(580,n.y))});return list;
 },[events]);
 useEffect(()=>{stored.current=new Map(nodes.map(n=>[n.id,{x:n.x,y:n.y}]))},[nodes]);
 const ids=new Set(visible.map(e=>e.event_id));
 const aIds=new Set(visible.flatMap(e=>[e.actor1?.code,e.actor2?.code]).filter(Boolean));
 const shown=nodes.filter(n=>n.event?ids.has(n.event.event_id):aIds.has(n.actor?.code));
 const highlighted=new Set(visible.filter(e=>selected?e.event_id===selected:actor==='unlinked'?!e.actor1&&!e.actor2:actor!=='all'&&(e.actor1?.code===actor||e.actor2?.code===actor)).map(e=>e.event_id));
 const linkedActors=new Set(visible.filter(e=>highlighted.has(e.event_id)).flatMap(e=>[e.actor1?.code,e.actor2?.code]));
 const map=new Map(nodes.map(n=>[n.id,n]));const point=(n:Node)=>moved[n.id]||n;
 const edges=visible.flatMap(e=>[...(e.actor1?[{from:'a:'+e.actor1.code,to:'e:'+e.event_id,label:'INITIATED',event:e}]:[]),...(e.actor2?[{from:'e:'+e.event_id,to:'a:'+e.actor2.code,label:'TARGETED',event:e}]:[]),...(e.parent_event_id&&ids.has(e.parent_event_id)?[{from:'e:'+e.parent_event_id,to:'e:'+e.event_id,label:'SCENARIO FROM',event:e}]:[])]);
 function coords(e:React.PointerEvent){const pt=svg.current!.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;return pt.matrixTransform(svg.current!.getScreenCTM()!.inverse())}
 return <div className="knowledge-graph"><svg ref={svg} viewBox="0 0 1000 640" className="network-svg" role="group" aria-label="Interactive graph. Click to highlight connected nodes; drag to move or pan." onPointerDown={e=>{if(e.target===e.currentTarget){const p=coords(e);drag.current={x:p.x,y:p.y,ox:camera.x,oy:camera.y,distance:0};e.currentTarget.setPointerCapture(e.pointerId)}}} onPointerMove={e=>{const d=drag.current;if(!d)return;const p=coords(e),dx=p.x-d.x,dy=p.y-d.y;d.distance=Math.max(d.distance,Math.hypot(dx,dy));if(d.id)setMoved(m=>({...m,[d.id!]:{x:d.ox+dx/camera.scale,y:d.oy+dy/camera.scale}}));else setCamera(c=>({...c,x:d.ox+dx,y:d.oy+dy}))}} onPointerUp={()=>setTimeout(()=>{drag.current=null},0)} onPointerCancel={()=>{drag.current=null}}><defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="4" markerHeight="4" orient="auto"><path d="M0 0 L10 5 L0 10z" fill="#4176cf"/></marker></defs><g transform={`translate(${camera.x} ${camera.y}) translate(500 320) scale(${camera.scale}) translate(-500 -320)`}>
 {edges.map(edge=>{const a=point(map.get(edge.from)!),b=point(map.get(edge.to)!),highlight=highlighted.has(edge.event.event_id);const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1;const bend=((hash(edge.from+edge.to)%3)-1)*.17;const cx=(a.x+b.x)/2-dy*bend,cy=(a.y+b.y)/2+dx*bend;return <g key={edge.from+edge.to} style={{pointerEvents:'none'}}><path d={`M${a.x} ${a.y} Q${cx} ${cy} ${b.x-dx/d*9} ${b.y-dy/d*9}`} fill="none" stroke={highlight?'#1661e8':edge.event.provenance==='simulated'?'#5987d7':'#aebbc9'} strokeWidth={highlight?1.7:.7} opacity={highlight?.85:.48} strokeDasharray={edge.event.provenance==='simulated'?'4 3':undefined} markerEnd={highlight?'url(#arrow)':undefined}/>{highlight&&selected&&<text x={cx} y={cy-5} className="edge-label">{edge.label}</text>}</g>})}
 {shown.map(n=>{const p=point(n),chosen=n.event?highlighted.has(n.event.event_id):n.actor!.code===actor||linkedActors.has(n.actor!.code);const simulated=n.event?.provenance==='simulated';const c=n.event?'#7497ca':n.actor!.actor_type==='org'?'#1966da':n.actor!.actor_type==='person'?'#172e50':'#111827';function activate(){if((drag.current?.distance||0)>4)return;n.event?onEvent(n.event.event_id):onActor(n.actor!.code)}return <g key={n.id} transform={`translate(${p.x} ${p.y})`} role="button" tabIndex={0} aria-pressed={chosen} aria-label={`${n.event?'Event':n.actor!.actor_type}: ${n.label}`} className={`graph-node ${simulated?'sim-node':''}`} onClick={activate} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();n.event?onEvent(n.event.event_id):onActor(n.actor!.code)}}} onPointerDown={e=>{e.stopPropagation();const pos=coords(e);drag.current={id:n.id,x:pos.x,y:pos.y,ox:p.x,oy:p.y,distance:0};e.currentTarget.setPointerCapture(e.pointerId)}}><title>{n.label}{simulated?' — simulated, not observed':''}</title><circle r="14" fill="transparent"/>{chosen&&<circle r="15" fill="#216af51a" stroke="#216af5" strokeWidth=".7"/>}{n.event?<path d="M0 -4 L4 0 L0 4 L-4 0Z" fill={simulated?'white':chosen?'#1661e8':c} stroke={simulated?'#1661e8':'white'} strokeWidth="1"/>:<circle r={chosen?6:4.8} fill={chosen?'#1661e8':c} stroke="white" strokeWidth="1.3"/>}{(labels||chosen||n.actor)&&<text x="8" y="-7" className={chosen?'node-label focused':'node-label'}>{n.event?(chosen?n.label:`${simulated?'SIM':'EVT'} ${n.event.event_id.split('-').at(-1)}`):n.label}</text>}</g>})}
 </g></svg><div className="graph-tools"><button aria-label="Zoom in" onClick={()=>setCamera(c=>({...c,scale:Math.min(4,c.scale+.25)}))}>+</button><button aria-label="Zoom out" onClick={()=>setCamera(c=>({...c,scale:Math.max(.4,c.scale-.25)}))}>−</button><button aria-label="Reset view" onClick={()=>{setCamera({x:0,y:0,scale:1});setMoved({})}}>⌖</button></div><div className="graph-legend"><b>ENTITY TYPES</b><span><i style={{background:'#111827'}}/>Country / actor</span><span><i style={{background:'#1966da'}}/>Organization</span><span><i style={{background:'#172e50'}}/>Person</span><span><i style={{background:'#7497ca'}}/>Event</span><span>◇ Simulated event</span></div></div>
}
