"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import KnowledgeGraph from './knowledge-graph';
import Guide from './guide';
import {DEMO,WorldEvent} from '../lib/world';
import {pureEquilibria} from '../lib/payoffs.mjs';

export default function PredictorWorkspace(){
 const [about,setAbout]=useState(false),[records,setRecords]=useState<WorldEvent[]>(DEMO),[scenarios,setScenarios]=useState<WorldEvent[]>([]);
 const [live,setLive]=useState(false),[feedError,setFeedError]=useState(''),[lastSync,setLastSync]=useState(''),[syncing,setSyncing]=useState(false);
 const [key,setKey]=useState(''),[selected,setSelected]=useState<string>(),[actor,setActor]=useState('all'),[search,setSearch]=useState(''),[ledger,setLedger]=useState(false),[labels,setLabels]=useState(false);
 const [baseId,setBaseId]=useState(''),[strategy,setStrategy]=useState('alternating'),[steps,setSteps]=useState(1),[running,setRunning]=useState(false),[stopping,setStopping]=useState(false),[elapsed,setElapsed]=useState(0),[completed,setCompleted]=useState(0),[error,setError]=useState(''),[activity,setActivity]=useState<string[]>([]);
 const busy=useRef(false),stop=useRef(false),mounted=useRef(true);
 const [anchors,setAnchors]=useState<WorldEvent[]>([]);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;stop.current=true}},[]);
 useEffect(()=>{
  let disposed=false,fetching=false;
  async function poll(){if(fetching)return;fetching=true;setSyncing(true);
   try{const response=await fetch('/api/events',{cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error||'Event service unavailable.');if(!Array.isArray(data)||!data.length)throw Error('No recorded events loaded yet.');if(!data.every(e=>typeof e.event_id==='string'&&Number.isFinite(Date.parse(e.timestamp))&&Number.isFinite(e.goldstein_scale)&&Number.isFinite(e.avg_tone)))throw Error('Invalid event records.');if(!disposed){setRecords(Array.from(new Map(data.map(e=>[e.event_id,{...e,provenance:'recorded'} as WorldEvent])).values()));setLive(true);setLastSync(new Date().toLocaleTimeString());setFeedError('')}}
   catch(e){if(!disposed)setFeedError(e instanceof Error?e.message:'Cannot reach event service.')}
   finally{fetching=false;if(!disposed)setSyncing(false)}
  }poll();const timer=setInterval(poll,15000);return()=>{disposed=true;clearInterval(timer)};
 },[]);
 useEffect(()=>{if(!running)return;setElapsed(0);const timer=setInterval(()=>setElapsed(n=>n+1),1000);return()=>clearInterval(timer)},[running]);
 const eligible=useMemo(()=>records.filter(e=>e.actor1&&e.actor2&&e.actor1.code!==e.actor2.code),[records]);
 const base=eligible.find(e=>e.event_id===baseId)||eligible[0];
 const all=useMemo(()=>Array.from(new Map([...anchors,...records,...scenarios].map(e=>[e.event_id,e])).values()),[anchors,records,scenarios]);
 const visible=useMemo(()=>all.filter(e=>!search||[e.title,e.event_id,e.actor1?.name,e.actor2?.name,e.event_code].join(' ').toLowerCase().includes(search.toLowerCase())),[all,search]);
 const picked=all.find(e=>e.event_id===selected),result=picked?.agent_step?picked:scenarios.at(-1);
 const actorCount=new Set(records.flatMap(e=>[e.actor1?.code,e.actor2?.code]).filter(Boolean)).size;
 const mean=records.length?records.reduce((s,e)=>s+e.goldstein_scale,0)/records.length:0;
 function selectEvent(id:string){setSelected(id);setActor('all');if(eligible.some(e=>e.event_id===id))setBaseId(id)}
 async function run(){
  if(busy.current||!key.trim()||!base)return;busy.current=true;stop.current=false;setRunning(true);setStopping(false);setError('');setCompleted(0);
  const runKey=key.trim(),runStrategy=strategy,runSteps=steps,runId=Date.now();let current=base;
  setAnchors(a=>a.some(e=>e.event_id===base.event_id)?a:[...a,base]);
  const history=records.filter(e=>Date.parse(e.timestamp)<=Date.parse(base.timestamp)).sort((a,b)=>Date.parse(a.timestamp)-Date.parse(b.timestamp));
  const log=(message:string)=>setActivity(a=>[`${new Date().toLocaleTimeString()} — ${message}`,...a].slice(0,30));
  log(`Started ${runSteps}-step ${live?'recorded-data':'demo-data'} scenario: ${base.actor1.name} / ${base.actor2.name}.`);
  try{for(let i=0;i<runSteps&&!stop.current;i++){
   const related=history.filter(e=>[e.actor1?.code,e.actor2?.code].some(c=>c===base.actor1.code||c===base.actor2.code)).slice(-12);
   const response=await fetch('/api/agent-step',{method:'POST',headers:{'Content-Type':'application/json','X-Anthropic-Api-Key':runKey},body:JSON.stringify({base:current,history:related,strategy:runStrategy})});
   const data=await response.json();if(!response.ok)throw Error(data.error||'The simulation request failed.');if(!mounted.current)break;
   const st=data.step;const next:WorldEvent={event_id:`sim-${runId}-${i+1}`,event_code:st.event_code,title:st.event_title,goldstein_scale:st.goldstein_scale,avg_tone:0,timestamp:new Date(Date.parse(current.timestamp)+900000).toISOString(),source_url:'',actor1:base.actor1,actor2:base.actor2,location:base.location,provenance:'simulated',parent_event_id:current.event_id,rationale:st.rationale,agent_step:st};
   setScenarios(a=>[...a,next]);setSelected(next.event_id);setActor('all');setCompleted(i+1);log(`Step ${i+1} complete. Matrix validated; hypothetical event added.`);history.push(next);history.sort((a,b)=>Date.parse(a.timestamp)-Date.parse(b.timestamp));current=next;
  }}catch(e){if(mounted.current){const message=e instanceof Error?e.message:'Simulation failed.';setError(message);log(message)}}finally{busy.current=false;if(mounted.current){setRunning(false);setStopping(false);log(stop.current?'Stopped after the current request.':'Run finished.')}}
 }
 return <div className="app-shell"><header className="site-header"><div className="project-name">Temporal Knowledge Graph Engine<br/><span>for Geopolitical Event Forecasting</span></div><nav aria-label="Main navigation"><button className={!about?'active':''} onClick={()=>setAbout(false)}>Workspace</button><button className={about?'active':''} onClick={()=>setAbout(true)}>How it works</button></nav></header>{about?<Guide/>:<main>
 <section className="feed-status"><div><span className="status-dot"/><strong>Feed watcher is always on</strong> <span className="badge">{live?'Recorded events':'Demo data'}</span><p>{feedError?`${feedError} ${live?'Keeping the last successful snapshot.':'Showing synthetic sample events.'}`:'Checking the event service every 15 seconds. New records update the graph automatically.'}</p></div><div className="feed-time">{syncing?'Checking for events…':lastSync?`Last successful check ${lastSync}`:'Waiting for the event service'}<small>Up to 500 records · ingestion runs separately</small></div></section>
 <div className="page-heading"><div><p className="eyebrow">EXPLORE → COMPARE → SIMULATE</p><h1>Explore events. Examine possible responses.</h1><p>Follow connections between actors and events, then inspect the assumptions behind a hypothetical next move.</p></div><button onClick={()=>setAbout(true)}>Understand the method ↗</button></div>
 <section className="card setup"><div className="section-heading"><h2>Set up a simulation</h2><span className="muted">Exploring is free. Model requests use your key.</span></div><div className="setup-grid">
 <div><span className="step-number">1</span><h3>Add your Anthropic API key</h3><label htmlFor="api-key">Your key</label><div className="key-input"><input id="api-key" type="password" autoComplete="off" spellCheck={false} placeholder="sk-ant-…" value={key} disabled={running} onChange={e=>setKey(e.target.value)}/>{key&&<button disabled={running} onClick={()=>setKey('')}>Clear</button>}</div><p>Held in page memory and sent through this server to Anthropic. Cleared on reload. {key.trim()?'Entered; verified only when you run.':'No shared project key is used.'}</p><a href="https://console.anthropic.com/settings/keys" target="_blank" rel="noreferrer">Get an Anthropic key ↗</a></div>
 <div><span className="step-number">2</span><h3>Choose the starting event</h3><label htmlFor="base-event">Two-actor event</label><select id="base-event" disabled={running} value={base?.event_id||''} onChange={e=>{setBaseId(e.target.value);setSelected(e.target.value)}}>{eligible.map(e=><option key={e.event_id} value={e.event_id}>{e.actor1.name} / {e.actor2.name} · {e.title||e.event_code}</option>)}</select><p>Or select an event in the graph. Each run keeps this actor pair and builds on its previous hypothetical step.</p><span className="badge">{live?'Recorded starting evidence':'Synthetic starting evidence'}</span></div>
 <div><span className="step-number">3</span><h3>Choose a scenario and run</h3><div className="form-pair"><label>Scenario hint<select disabled={running} value={strategy} onChange={e=>setStrategy(e.target.value)}><option value="alternating">Unconstrained</option><option value="cooperation">Cooperation</option><option value="escalation">Escalation</option></select></label><label>Steps<select disabled={running} value={steps} onChange={e=>setSteps(Number(e.target.value))}>{[1,5,10,50].map(n=><option key={n}>{n}</option>)}</select></label></div><button className="primary run-button" disabled={!key.trim()||!base||running} onClick={run}>{running?'Simulation in progress…':`Run ${steps===1?'one step':`${steps} steps`}`}</button><p>{!key.trim()?'Add your key to enable simulation. ':''}One model generation per step, with automatic retries. Usage is billed to your Anthropic account.</p></div>
 </div></section>
 <section className={`run-status ${running?'is-running':''}`} aria-live="polite"><div><strong>{running?`Waiting for model response · step ${completed+1} of ${steps}`:completed?`${completed} step${completed===1?'':'s'} completed`:'Ready to explore'}</strong><p>{running?`${elapsed}s elapsed in this run. The graph changes only when a complete response arrives.`:'Simulation starts only when you run it. Generated events remain separate from recorded evidence.'}</p>{error&&<p className="error">{error}</p>}</div>{running&&<button disabled={stopping} onClick={()=>{stop.current=true;setStopping(true)}}>{stopping?'Stopping after this response…':'Stop after this step'}</button>}</section>
 <section className="card graph-card"><div className="section-heading"><div><h2>Event knowledge graph</h2><p>Select an actor to highlight connections. Select an event to inspect it.</p></div><div className="segmented"><button className={!ledger?'active':''} onClick={()=>setLedger(false)}>Graph</button><button className={ledger?'active':''} onClick={()=>setLedger(true)}>Event list</button></div></div><div className="graph-toolbar"><input aria-label="Search graph" placeholder="Search actors or events…" value={search} onChange={e=>setSearch(e.target.value)}/><label><input type="checkbox" checked={labels} onChange={e=>setLabels(e.target.checked)}/> Event labels</label><button onClick={()=>{setSelected(undefined);setActor('all');setSearch('')}}>Clear selection</button><span>{records.length} evidence events · {actorCount} actors · {scenarios.length} simulated</span></div>
 <div className="graph-workspace"><div className="graph-stage">{ledger?<div className="event-list">{visible.map(e=><button key={e.event_id} className={selected===e.event_id?'selected':''} onClick={()=>selectEvent(e.event_id)}><span className="badge">{e.provenance||'demo'}</span><strong>{e.title||`Event ${e.event_code}`}</strong><span>{e.actor1?.name||'Unlinked'} → {e.actor2?.name||'No target'}</span><small>{e.timestamp.slice(0,16).replace('T',' ')} UTC</small></button>)}</div>:<KnowledgeGraph events={all} visible={visible} selected={selected} actor={actor} onActor={code=>{setActor(code);setSelected(undefined)}} onEvent={selectEvent} labels={labels}/>}</div>
 <aside className="inspector"><p className="eyebrow">SELECTION DETAILS</p>{picked?<><span className="badge">{picked.provenance||'demo'}</span><h3>{picked.title||`Event ${picked.event_code}`}</h3><dl><dt>Initiating actor / row player</dt><dd>{picked.actor1?.name||'Unknown'}</dd><dt>Target actor / column player</dt><dd>{picked.actor2?.name||'Unknown'}</dd><dt>{picked.agent_step?'Scenario timestamp':'Event timestamp'}</dt><dd>{picked.timestamp.replace('T',' ').replace('.000Z',' UTC')}</dd><dt>Goldstein {picked.agent_step?'estimate':'score'}</dt><dd>{picked.goldstein_scale.toFixed(1)} <span className="muted">/ −10 to +10</span></dd><dt>Location</dt><dd>{picked.location?.name||'Not supplied'}</dd></dl>{picked.agent_step?<a href="#payoffs">Inspect this payoff matrix ↓</a>:picked.source_url&&/^https?:\/\//.test(picked.source_url)?<a href={picked.source_url} target="_blank" rel="noreferrer">Open source report ↗</a>:<p>No source report available.</p>}</>:actor!=='all'?<><h3>{all.flatMap(e=>[e.actor1,e.actor2]).find(a=>a?.code===actor)?.name}</h3><p>Connected events are blue. Other nodes remain visible.</p></>:<><h3>Start with a connection</h3><p>Circles are actors: countries, organizations, or people. Diamonds are events, including those with incomplete actor information.</p><p>Solid relationships describe evidence. Dashed relationships connect hypothetical steps.</p></>}<div className="inspector-note"><strong>Evidence snapshot</strong><p>Mean Goldstein: {mean.toFixed(2)}<br/>{records.length} events; simulated events excluded.</p><small>A noisy event-code measure, not a probability of conflict.</small></div></aside></div></section>
 <section id="payoffs" className="card results"><div className="section-heading"><div><p className="eyebrow">STRATEGIC ASSUMPTIONS</p><h2>Payoff matrix</h2></div>{scenarios.length>0&&<label>View generated step<select value={result?.event_id||''} onChange={e=>setSelected(e.target.value)}>{scenarios.map((e,i)=><option key={e.event_id} value={e.event_id}>{i+1}. {e.title}</option>)}</select></label>}</div>{result?<Payoffs event={result}/>:<div className="empty-result"><span className="empty-grid">▦</span><h3>Your first run will appear here</h3><p>Rows will show the first actor’s actions; columns, the second actor’s actions. Every cell will show both estimated payoffs, with the model’s chosen outcome marked.</p><p>No results or probabilities are invented before you run a simulation.</p></div>}</section>
 <details className="card activity"><summary>Run activity <span className="muted">{activity.length} entries</span></summary>{activity.length?activity.map((line,i)=><p key={i}>{line}</p>):<p>No model requests made in this session.</p>}</details>
 <footer>Research interface · Hypothetical scenarios are not calibrated forecasts.<button onClick={()=>setAbout(true)}>Read assumptions and limitations ↗</button></footer></main>}</div>;
}

function Payoffs({event}:{event:WorldEvent}){
 const step=event.agent_step!;const equilibria=pureEquilibria(step.payoff_matrix);
 const row=step.actor1_options.indexOf(step.chosen_actor1_action),col=step.actor2_options.indexOf(step.chosen_actor2_action),stable=equilibria.some(([r,c])=>r===row&&c===col);
 return <><div className="matrix-intro"><h3>{event.actor1?.name} × {event.actor2?.name}</h3><p>Read each pair as <strong className="blue">{event.actor1?.name}’s payoff</strong>, then <strong>{event.actor2?.name}’s payoff</strong>. Higher means more favorable to that actor. These numbers are model assumptions, not measured benefits or probabilities.</p></div><p className="axis-label">Columns: {event.actor2?.name}’s possible actions →</p><div className="matrix-scroll"><table className="payoff-table"><caption>Rows: {event.actor1?.name}’s possible actions</caption><thead><tr><th scope="col">{event.actor1?.name} ↓ / {event.actor2?.name} →</th>{step.actor2_options.map((option,j)=><th scope="col" key={j}>{option}</th>)}</tr></thead><tbody>{step.actor1_options.map((option,i)=><tr key={i}><th scope="row">{option}</th>{step.payoff_matrix[i].map((pair,j)=>{const chosen=i===row&&j===col,eq=equilibria.some(([r,c])=>r===i&&c===j);return <td key={j} className={chosen?'chosen':''}><div className="payoff-pair"><span className="blue">{pair[0]}</span><span className="comma">,</span><span>{pair[1]}</span></div><div className="cell-markers">{chosen&&<span>Model choice</span>}{eq&&<span>Pure equilibrium</span>}</div></td>})}</tr>)}</tbody></table></div><div className="reasoning-grid"><div><h3>Chosen hypothetical outcome</h3><p><strong>{event.actor1?.name}:</strong> {step.chosen_actor1_action}<br/><strong>{event.actor2?.name}:</strong> {step.chosen_actor2_action}</p><p>{event.rationale}</p></div><div><h3>Independent matrix check</h3><p>{equilibria.length?`${equilibria.length} pure-strategy equilibrium cell${equilibria.length===1?'':'s'} found. ${stable?'The model’s choice is one of them.':'The model’s choice is not a pure equilibrium.'}`:'No pure-strategy equilibrium found. Mixed strategies are not calculated.'}</p><p>An equilibrium means neither actor can improve its payoff by changing its action alone, assuming these numbers are correct.</p><details><summary>Model’s own reasoning</summary><p>{step.equilibrium_note}</p></details></div></div><div className="assumption-note">Hypothetical event: {event.title}. Scenario timestamps advance 15 minutes per step for ordering only; they do not estimate when an event will occur.</div></>;
}
